[settings]
logging = true

[settings.automation]
user_ids = [0324726462364]
delete_interval = 1800
delete = true

[database]
host = "127.0.0.1"
port = 8058
username = "someone"
password = "someone"
database = "discord"

